---
- name: Slurp vault-init.json from ops-vm
  slurp:
    src: /root/vault-init.json
  become: true
  delegate_to: "{{ groups['ops'][0] }}"
  register: netbox_vault_init_raw
  no_log: true

- name: Set vault root token
  set_fact:
    netbox_vault_root_token: "{{ (netbox_vault_init_raw.content | b64decode | from_json).root_token }}"
  no_log: true

- name: Fetch NetBox secrets from Vault
  uri:
    url: "https://127.0.0.1:8200/v1/secret/data/netbox"
    method: GET
    headers:
      X-Vault-Token: "{{ netbox_vault_root_token }}"
    ca_path: /etc/ssl/internal/ca.crt
    status_code: 200
  delegate_to: "{{ groups['ops'][0] }}"
  register: netbox_vault_secrets
  no_log: true

- name: Set NetBox secrets from Vault
  set_fact:
    netbox_password: "{{ netbox_vault_secrets.json.data.data.password }}"
    netbox_api_token: "{{ netbox_vault_secrets.json.data.data.api_token }}"
    netbox_secret_key: "{{ netbox_vault_secrets.json.data.data.secret_key }}"
  no_log: true
