<?xml version="1.0"?>
<pfsense>
	<version>23.3</version>
	<lastchange></lastchange>
	<system>
		<setupwizardcomplete></setupwizardcomplete>
		<enablesshd>yes</enablesshd>
		<dnsserver>1.1.1.1</dnsserver>
		<dnsserver>8.8.8.8</dnsserver>
		<optimization>normal</optimization>
		<hostname>pfSense-Cloud</hostname>
		<domain>home.arpa</domain>
		<dnsallowoverride></dnsallowoverride>
		<group>
			<name>all</name>
			<description><![CDATA[All Users]]></description>
			<scope>system</scope>
			<gid>1998</gid>
			<member>0</member>
		</group>
		<group>
			<name>admins</name>
			<description><![CDATA[System Administrators]]></description>
			<scope>system</scope>
			<gid>1999</gid>
			<member>0</member>
			<priv>page-all</priv>
		</group>
		<user>
			<name>admin</name>
			<descr><![CDATA[System Administrator]]></descr>
			<scope>system</scope>
			<groupname>admins</groupname>
			<bcrypt-hash>$2b$10$13u6qwCOwODv34GyCMgdWub6oQF3RX0rG7c3d3X4JvzuEmAXLYDd2</bcrypt-hash>
			<uid>0</uid>
			<priv>user-shell-access</priv>
			<authorizedkeys>${admin_authorized_keys_b64}</authorizedkeys>
		</user>
		<nextuid>2000</nextuid>
		<nextgid>2000</nextgid>
		<timeservers>2.pfsense.pool.ntp.org</timeservers>
		<webgui>
			<protocol>https</protocol>
			<loginautocomplete></loginautocomplete>
		</webgui>
		<disablenatreflection>yes</disablenatreflection>
		<disablesegmentationoffloading></disablesegmentationoffloading>
		<disablelargereceiveoffloading></disablelargereceiveoffloading>
		<ipv6allow></ipv6allow>
		<maximumtableentries>400000</maximumtableentries>
		<ssh>
			<enable>enabled</enable>
		</ssh>
	</system>
	<interfaces>
		<wan>
			<enable></enable>
			<if>vtnet0</if>
			<mtu></mtu>
			<ipaddr>10.0.1.2</ipaddr>
			<ipaddrv6></ipaddrv6>
			<subnet>30</subnet>
			<gateway>WANGW</gateway>
			<dhcphostname></dhcphostname>
			<media></media>
			<mediaopt></mediaopt>
		</wan>
		<lan>
			<enable></enable>
			<if>vtnet1</if>
			<ipaddr>192.168.255.254</ipaddr>
			<subnet>28</subnet>
		</lan>
		<opt1>
			<enable></enable>
			<if>vtnet2</if>
			<descr>DMZ</descr>
			<ipaddr>10.255.255.254</ipaddr>
			<subnet>29</subnet>
		</opt1>
	</interfaces>
	<staticroutes></staticroutes>
	<dhcpd>
		<lan>
			<enable></enable>
			<range>
				<from>192.168.255.241</from>
				<to>192.168.255.253</to>
			</range>
		</lan>
		<opt1>
			<enable></enable>
			<range>
				<from>10.255.255.249</from>
				<to>10.255.255.253</to>
			</range>
		</opt1>
	</dhcpd>
	<nat>
		<outbound>
			<mode>automatic</mode>
		</outbound>
	</nat>
	<filter>
		<rule>
			<type>pass</type>
			<ipprotocol>inet</ipprotocol>
			<descr><![CDATA[Default allow LAN to any rule]]></descr>
			<interface>lan</interface>
			<tracker>0100000101</tracker>
			<source>
				<network>lan</network>
			</source>
			<destination>
				<any></any>
			</destination>
		</rule>
	</filter>
	<gateways>
		<gateway_item>
			<interface>wan</interface>
			<gateway>10.0.1.1</gateway>
			<name>WANGW</name>
			<weight>1</weight>
			<ipprotocol>inet</ipprotocol>
			<interval></interval>
			<descr><![CDATA[Interface wan Gateway]]></descr>
		</gateway_item>
		<defaultgw4>WANGW</defaultgw4>
	</gateways>
	<unbound>
		<enable></enable>
	</unbound>
</pfsense>
