all:
  children:
    services:
      hosts:
        services-vm:
          ansible_host: 172.16.0.241
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    vault:
      hosts:
        vault-vm:
          ansible_host: 172.16.0.242
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    pfsense:
      hosts:
        pfsense-fw-01:
          ansible_host: 172.16.0.254
          ansible_user: admin
          ansible_password: "pfsense"
          ansible_connection: ssh
          ansible_python_interpreter: /usr/local/bin/python3.11
