---
- name: Deploy NetBox sync agent on all VMs
  hosts: services:ops
  become: true
  vars:
    netbox_api_token: "0123456789abcdef0123456789abcdef01234567"
    netbox_remote_url: "http://172.16.0.241:8080"
  tasks:
    - import_tasks: ../roles/netbox/tasks/sync_agent.yml
