vault_version: "1.15.4"
vault_addr: "https://172.16.255.243:8200"
vault_data_dir: "/opt/vault/data"
vault_tls_dir: "/opt/vault/tls"
vault_log_dir: "/var/log/vault"
vault_user: "vault"
vault_group: "vault"
vault_api_addr: "https://172.16.255.243:8200"
vault_cluster_addr: "https://172.16.255.243:8201"