---
- name: "[KILLSWITCH] Désactiver le serveur OpenVPN"
  pfsensible.core.pfsense_openvpn_server:
    name: "{{ openvpn_server.name }}"
    mode: "{{ openvpn_server.mode }}"
    protocol: "{{ openvpn_server.protocol }}"
    interface: "{{ openvpn_server.interface }}"
    local_port: "{{ openvpn_server.local_port }}"
    tunnel_network: "{{ openvpn_server.tunnel_network }}"
    remote_network: "{{ openvpn_server.remote_network }}"
    shared_key: "{{ openvpn_shared_key }}"
    data_ciphers: "{{ openvpn_server.data_ciphers }}"
    compression: "{{ openvpn_server.compression }}"
    disable: true
    state: present
  tags: [never, killswitch]

- name: "[RESTORE] Supprimer la règle KILLSWITCH si présente"
  pfsensible.core.pfsense_rule:
    name: "KILLSWITCH_OpenVPN_1194"
    interface: wan
    state: absent
  tags: [never, restore]

- name: "[RESTORE] Rétablir/Activer le serveur OpenVPN"
  pfsensible.core.pfsense_openvpn_server:
    name: "{{ openvpn_server.name }}"
    mode: "{{ openvpn_server.mode }}"
    protocol: "{{ openvpn_server.protocol }}"
    interface: "{{ openvpn_server.interface }}"
    local_port: "{{ openvpn_server.local_port }}"
    tunnel_network: "{{ openvpn_server.tunnel_network }}"
    remote_network: "{{ openvpn_server.remote_network }}"
    shared_key: "{{ openvpn_shared_key }}"
    data_ciphers: "{{ openvpn_server.data_ciphers }}"
    compression: "{{ openvpn_server.compression }}"
    disable: false
    state: present
  tags: [never, restore]
