---
- name: Configurer la clé SSH autorisée pour admin
  pfsensible.core.pfsense_user:
    name: admin
    authorizedkeys: "{{ ssh_public_key }}"
    state: present
  tags: [configure, ssh]

#- name: Configure interfaces
#  import_tasks: interfaces.yml

- name: Configure firewall rules
  import_tasks: firewall.yml

- name: Configure OpenVPN
  import_tasks: openvpn.yml

- name: Configure DNS
  import_tasks: dns.yml

- name: Configure killswitch
  import_tasks: killswitch.yml
