---
filebeat_version: "8.13.0"
# Ancien: elk_elasticsearch_host: "172.16.0.253"  ← IP hardcodée
filebeat_elasticsearch_host: "{{ hostvars[groups['ops'][0]]['ansible_host'] }}"
filebeat_elasticsearch_port: 9200
filebeat_elastic_password: "changeme"
filebeat_tls_ca_path: /etc/ssl/internal/ca.crt
