name: Mirror Repository

on:
  push:
    branches:
      - main
      - mirror-job

jobs:
  mirror:
    name: Mirror to Epitech Repo
    runs-on: ubuntu-latest
    if: github.repository == 'DGSI-Epitech/infra'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror to Epitech repository
        run: |
          git remote add epitech https://${{ secrets.MIRROR_SSH_KEY }}@github.com/EpitechMscProPromo2027/T-NSA-810-PAR_15.git
          git push --mirror epitech