name: Build Packer Template

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "packer/**"

jobs:
  build-template:
    name: Build Ubuntu 22.04 template
    runs-on: self-hosted
    defaults:
      run:
        working-directory: packer/ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: "latest"

      - name: Packer init
        run: packer init .

      - name: Packer validate
        run: packer validate -var-file=ubuntu-22.04.pkrvars.hcl .
        env:
          PKR_VAR_proxmox_token: ${{ secrets.PROXMOX_PACKER_TOKEN }}
          PKR_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
          PKR_VAR_ssh_private_key_file: ${{ secrets.SSH_PRIVATE_KEY_FILE }}
          PKR_VAR_ssh_bastion_private_key_file: ${{ secrets.SSH_PRIVATE_KEY_FILE }}

      - name: Packer build
        run: packer build -var-file=ubuntu-22.04.pkrvars.hcl .
        env:
          PKR_VAR_proxmox_token: ${{ secrets.PROXMOX_PACKER_TOKEN }}
          PKR_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
          PKR_VAR_ssh_private_key_file: ${{ secrets.SSH_PRIVATE_KEY_FILE }}
          PKR_VAR_ssh_bastion_private_key_file: ${{ secrets.SSH_PRIVATE_KEY_FILE }}
